parameters:
  # MemberManagementBundle actions
  # actionname: id
  # Make sure that keys are unique.
  actions:
      member_added:                         17
      member_removed:                       18
      member_group_added:                   19
      member_group_removed:                 20
      member_username_updated:              21
      member_password_updated:              22
      member_email_updated:                 23
      member_activated_self:                24
      member_activated_admin:               25
      member_status_updated:                26
      member_banned:                        27
      member_ban_removed:                   28
      member_registered:                    29
      member_added_to_group:                30
      member_removed_from_group:            31
      member_bulk_add_to_group:             32
      member_bulk_remove_from_group:        33
      member_added_to_site:                 34
      member_bulk_add_to_site:              35
      member_removed_from_site:             36
      member_bulk_remove_from_site:         37
      member_language_updated:              38
      member_avatar_deleted:                39
      member_avatar_added:                  40
      member_avatar_updated:                41
      member_name_first_updated:            42
      member_name_last_updated:             43
      member_details_updated:               44