#accountLogin:
#    pattern:  manage/account/login
#    defaults: { _controller: BiberLtdBundleMemberManagementBundle:Account:login}
#processLogin:
#    pattern:  process/login/{redirect}
#    defaults: { _controller: BiberLtdBundleMemberManagementBundle:Process:login, redirect: "dashboard" }
#processLogout:
#    pattern:  process/logout/{backto}
#    defaults: { _controller: BiberLtdBundleMemberManagementBundle:Process:logout, backto: "account-login" }
#processRemind:
#    pattern:  process/remind/{backto}
#    defaults: { _controller: BiberLtdBundleMemberManagementBundle:Process:remind, backto: "account-login" }
