services:
    newsletter.model:
            class:        BiberLtd\Bundle\NewsletterBundle\Services\NewsletterModel
            arguments:    [@kernel, "default", "doctrine"]
    newsletterrender.model:
            class:        BiberLtd\Bundle\NewsletterBundle\Controller\RenderController
            arguments:    [@templating]